### ISSUE TITLE
Randomize Member Highlight Section

### ISSUE THREAD

**Issue by swindleNswoon** [swindleNswoon/bronxCodeCamp#1]
Member Highlight Section should randomly load people added to the members page, So that different members are displayed every time home page loads

**Comment by kemcrimmins** [comment]
Idea for this (until we have backend and a database):

var members = [{name: "Brian Lynch", photo: "<image url>", description: "ipsum lorem", website:  null}, {name: "Kem Crimmins", photo: null, description: null, website: null}];

It's an array of objects, so we can use a randomization on array.length (like how those who did Random Quote with own array of quotes rather than API).

If member doesn't have a website, for example, set that value to null so we know how to handle the dynamic loading--either not to load that element or to load a filler. (e.g., for photo with value of null load url for a photo of a kitten writing javascript.)

**Comment by kemcrimmins** [comment]
I'll do this over the weekend. I'll also set up the script so that it can be used to dynamically load the members page.

**Comment by swindleNswoon** [comment]
See code by Kem, nice work man
